platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

source 'https://github.com/appodeal/CocoaPods.git'
source 'https://github.com/CocoaPods/Specs.git'

def appodeal
  pod 'RNAppodeal', :path => '../../RNAppodeal.podspec' 
  pod 'APDAdColonyAdapter', '2.6.4.1'
  pod 'APDAmazonAdsAdapter', '2.6.4.1'
  pod 'APDAppLovinAdapter', '2.6.4.1'
  pod 'APDAppodealAdExchangeAdapter', '2.6.4.1'
  pod 'APDChartboostAdapter', '2.6.4.1'
  pod 'APDFacebookAudienceAdapter', '2.6.4.1'
  pod 'APDGoogleAdMobAdapter', '2.6.4.1'
  pod 'APDInMobiAdapter', '2.6.4.1'
  pod 'APDInnerActiveAdapter', '2.6.4.1'
  pod 'APDIronSourceAdapter', '2.6.4.1'
  pod 'APDMintegralAdapter', '2.6.4.1'
  pod 'APDMyTargetAdapter', '2.6.4.1'
  pod 'APDOguryAdapter', '2.6.4.1'
  pod 'APDOpenXAdapter', '2.6.4.1'
  pod 'APDPubnativeAdapter', '2.6.4.1'
  pod 'APDSmaatoAdapter', '2.6.4.1'
  pod 'APDStartAppAdapter', '2.6.4.1'
  pod 'APDTapjoyAdapter', '2.6.4.1' 
  pod 'APDUnityAdapter', '2.6.4.1'
  pod 'APDVungleAdapter', '2.6.4.1'
  pod 'APDYandexAdapter', '2.6.4.1'
end

target 'Example' do
  # Pods for Example
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/callinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga', :modular_headers => true

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  appodeal

  target 'ExampleTests' do
    inherit! :complete
    # Pods for testing
  end

  use_native_modules!
  use_frameworks!
end

