platform :ios, '11.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'

install! 'cocoapods', :warn_for_multiple_pod_sources => false

source 'https://github.com/appodeal/CocoaPods.git'
source 'https://cdn.cocoapods.org/'


def appodeal
  pod 'APDAdColonyAdapter', '3.0.0.1-Beta'
  pod 'APDAdjustAdapter', '3.0.0.1-Beta'
  pod 'APDAmazonAdsAdapter', '3.0.0.1-Beta'
  pod 'APDAppLovinAdapter', '3.0.0.1-Beta'
  pod 'APDAppsFlyerAdapter', '3.0.0.1-Beta'
  pod 'APDBidMachineAdapter', '3.0.0.1-Beta' # Required
  pod 'APDFirebaseAdapter', '3.0.0.1-Beta'
  pod 'APDGoogleAdMobAdapter', '3.0.0.1-Beta'
  pod 'APDIABAdapter', '3.0.0.1-Beta' # Required
  pod 'APDIronSourceAdapter', '3.0.0.1-Beta'
  pod 'APDFacebookAdapter', '3.0.0.1-Beta'
  pod 'APDMetaAudienceNetworkAdapter', '3.0.0.1-Beta'
  pod 'APDMyTargetAdapter', '3.0.0.1-Beta'
  pod 'APDStackAnalyticsAdapter', '3.0.0.1-Beta' # Required
  pod 'APDUnityAdapter', '3.0.0.1-Beta'
  pod 'APDVungleAdapter', '3.0.0.1-Beta'
  pod 'APDYandexAdapter', '3.0.0.1-Beta'
end

target 'Example' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false
  )

  appodeal

  target 'ExampleTests' do
    inherit! :complete
  end

  use_native_modules!
  use_frameworks!
end

post_install do |installer|
  react_native_post_install(installer)
  __apply_Xcode_12_5_M1_post_install_workaround(installer)
end