ENV['RCT_NEW_ARCH_ENABLED'] = '1'
ENV['USE_FRAMEWORKS'] = 'static'

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

project 'AppodealExample.xcodeproj'

source 'https://github.com/appodeal/CocoaPods.git'
source 'https://github.com/bidon-io/CocoaPods-Specs.git'
source 'https://cdn.cocoapods.org'

# Appodeal SDK 4.2.0
def appodeal
  pod 'Appodeal', '4.2.0'
  # AppLovin MAX
  pod 'AppLovinMediationAmazonAdMarketplaceAdapter', '5.3.2.0'
  pod 'AppLovinMediationBidMachineAdapter', '3.7.1.0.0'
  pod 'AppLovinMediationBigoAdsAdapter', '5.0.0.0'
  pod 'AppLovinMediationByteDanceAdapter', '7.7.0.7.0'
  pod 'AppLovinMediationChartboostAdapter', '9.10.1.0'
  pod 'AppLovinMediationFacebookAdapter', '6.20.1.0'
  pod 'AppLovinMediationFyberAdapter', '8.4.1.0'
  pod 'AppLovinMediationGoogleAdManagerAdapter', '12.13.0.0'
  pod 'AppLovinMediationGoogleAdapter', '12.13.0.0'
  pod 'AppLovinMediationInMobiAdapter', '11.1.0.0'
  pod 'AppLovinMediationIronSourceAdapter', '9.1.0.0.0'
  pod 'AppLovinMediationMintegralAdapter', '7.7.9.0.0'
  pod 'AppLovinMediationMobileFuseAdapter', '1.9.3.0'
  pod 'AppLovinMediationMolocoAdapter', '4.1.0.0'
  pod 'AppLovinMediationMyTargetAdapter', '5.36.2.0'
  pod 'AppLovinMediationOguryPresageAdapter', '5.1.1.0'
  pod 'AppLovinMediationPubMaticAdapter', '4.10.0.0'
  pod 'AppLovinMediationSmaatoAdapter', '23.1.0.0'
  pod 'AppLovinMediationUnityAdsAdapter', '4.16.3.0'
  pod 'AppLovinMediationVerveAdapter', '3.8.1.0'
  pod 'AppLovinMediationVungleAdapter', '7.6.2.0'
  pod 'AppLovinMediationYandexAdapter', '7.17.0.0'
  # Level Play
  pod 'IronSourceAdMobAdapter', '5.3.0.0'
  pod 'IronSourceAppLovinAdapter', '5.3.0.0'
  pod 'IronSourceBidMachineAdapter', '5.7.0.0'
  pod 'IronSourceBigoAdapter', '5.1.0.0'
  pod 'IronSourceFacebookAdapter', '5.0.0.0'
  pod 'IronSourceFyberAdapter', '5.2.0.0'
  pod 'IronSourceInMobiAdapter', '5.3.0.0'
  pod 'IronSourceMintegralAdapter', '5.1.0.0'
  pod 'IronSourceMobileFuseAdapter', '5.0.0.0'
  pod 'IronSourceMolocoAdapter', '5.2.0.0'
  pod 'IronSourceMyTargetAdapter', '5.3.0.0'
  pod 'IronSourceOguryAdapter', '5.0.0.0'
  pod 'IronSourcePangleAdapter', '5.5.0.0'
  pod 'IronSourceSmaatoAdapter', '5.2.0.0'
  pod 'IronSourceUnityAdsAdapter', '5.2.0.0'
  pod 'IronSourceVerveAdapter', '5.5.0.0'
  pod 'IronSourceVungleAdapter', '5.3.0.0'
  # Appodeal
  pod 'AppodealAdjustAdapter', '5.4.6.1'
  pod 'AppodealAmazonAdapter', '5.3.2.0'
  pod 'AppodealAppLovinAdapter', '13.5.1.0'
  pod 'AppodealAppLovinMAXAdapter', '13.5.1.1'
  pod 'AppodealAppsFlyerAdapter', '6.17.7.1'
  pod 'AppodealBidMachineAdapter', '3.7.1.0'
  pod 'AppodealBidonAdapter', '0.15.0.0'
  pod 'AppodealBigoAdsAdapter', '5.0.0.0'
  pod 'AppodealDTExchangeAdapter', '8.4.1.0'
  pod 'AppodealFacebookAdapter', '18.0.1.0'
  pod 'AppodealFirebaseAdapter', '12.4.0.1'
  pod 'AppodealGoogleAdMobAdapter', '12.13.0.0'
  pod 'AppodealIABAdapter', '3.5.0.0'
  pod 'AppodealInMobiAdapter', '11.1.0.0'
  pod 'AppodealIronSourceAdapter', '9.1.0.0.0'
  pod 'AppodealLevelPlayAdapter', '9.1.0.0.0'
  pod 'AppodealMetaAudienceNetworkAdapter', '6.20.1.0'
  pod 'AppodealMintegralAdapter', '7.7.9.0'
  pod 'AppodealMyTargetAdapter', '5.36.2.0'
  pod 'AppodealSentryAdapter', '8.57.2.1'
  pod 'AppodealUnityAdapter', '4.16.3.0'
  pod 'AppodealVungleAdapter', '7.6.2.0'
  pod 'AppodealYandexAdapter', '7.17.0.1'
  # Bidon
  pod 'BidonAdapterAmazon', '5.3.2.0'
  pod 'BidonAdapterAppLovin', '13.5.1.0'
  pod 'BidonAdapterBidMachine', '3.7.1.1'
  pod 'BidonAdapterBigoAds', '5.0.0.0'
  pod 'BidonAdapterChartboost', '9.10.1.0'
  pod 'BidonAdapterDTExchange', '8.4.1.0'
  pod 'BidonAdapterInMobi', '11.1.0.0'
  pod 'BidonAdapterIronSource', '9.1.0.0.0'
  pod 'BidonAdapterMetaAudienceNetwork', '6.20.1.0'
  pod 'BidonAdapterMintegral', '7.7.9.0'
  pod 'BidonAdapterMobileFuse', '1.9.3.0'
  pod 'BidonAdapterMoloco', '4.1.0.0'
  pod 'BidonAdapterMyTarget', '5.36.2.0'
  pod 'BidonAdapterStartIo', '4.13.0.0'
  pod 'BidonAdapterTaurusX', '1.15.0.0'
  pod 'BidonAdapterUnityAds', '4.16.3.0'
  pod 'BidonAdapterVungle', '7.6.2.0'
  pod 'BidonAdapterYandex', '7.17.0.0'
  pod 'BidonAdapterZmaticoo', '2.2.0.0'
end

target 'AppodealExample' do
  config = use_native_modules!
  use_modular_headers!
  appodeal
  
  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :hermes_enabled => true
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      :ccache_enabled => false
    )
  end
end
