export const LOADED             = 'onBannerLoaded'
export const FAILED_TO_LOAD     = 'onBannerFailedToLoad'
export const EXPIRED            = 'onBannerExpired'
export const SHOWN              = 'onBannerShown'
export const CLICKED            = 'onBannerClicked'