export const LOADED             = 'onInterstitialLoaded'
export const FAILED_TO_LOAD     = 'onInterstitialFailedToLoad'
export const SHOWN              = 'onInterstitialShown'
export const FAILED_TO_SHOW     = 'onInterstitialFaliedToShow'
export const CLICKED            = 'onInterstitialClicked'
export const CLOSED             = 'onInterstitialClosed'