export const LOADED             = 'onNonSkippableVideoLoaded'
export const FAILED_TO_LOAD     = 'onNonSkippableVideoFailedToLoad'
export const EXPIRED            = 'onNonSkippableVideoExpired'
export const SHOWN              = 'onNonSkippableVideoShown'
export const FAILED_TO_SHOW     = 'onNonSkippableVideoFailedToShow'
export const CLOSED             = 'onNonSkippableVideoClosed'
export const REWARD             = 'onNonSkippableVideoFinished'